name: Build-master

on:
  push:
    branches:
      - po-cn-master

jobs:
  build_html:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install dependencies with pip
        run: pip install --no-warn-script-location --user -r requirements.txt

      - name: Build the Html
        run: sphinx-build -b html -c . -D language=zh ./ _build/html_zh

      - name: Deploy Html documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./_build/html_zh
          publish_branch: gh-pages-cn-master
          
      # - name: Deploy to fishros.org
      #   run: echo `curl "http://fishros.org/deploy/github/action?url=git@github.com:fishros/navigation.ros.org.git&branch=gh-pages-cn-master&repository=navigation.ros.org&directory=&prefix=nav2"`